export const FILL_TASKS = 'FILL_TASKS';
export const FETCH_TASKS_ASYNC = 'FETCH_TASKS_ASYNC';
export const CREATE_TASK_ASYNC = 'CREATE_TASK_ASYNC';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK_ASYNC = 'DELETE_TASK_ASYNC';
export const DELETE_TASK = 'DELETE_TASK';
